Conditions are done
erdemalpay/coffeeroasters-subscription-site pull request #8
Opened 2021-08-13 12:56 UTC by esralpay

Conditions of coffee prefences are done according to the READ.me file criterias.

2021-08-13 13:18 UTC, erdemalpay requested changes
Seems good. I liked the dynamic variable assignment part ;) 
I have some comments, can you check them?

2021-08-13 13:18 UTC, erdemalpay commented on src/components/Subscribe.svelte
> +    //$: priceEveryweek = valueQuantity == "250g" ? "7.20" : valueQuantity == "500g" ? "13.00" : valueQuantity == "1000g" ? "22.00" : "0";
Let's remove this.

2021-08-13 13:18 UTC, erdemalpay commented on src/components/Subscribe.svelte
> +    let priceEveryweek = "";
Use camelCase for naming ie. `priceEveryWeek` not `priceEveryweek`

2021-08-13 13:18 UTC, erdemalpay commented on src/components/Subscribe.svelte
> +                class:selected={valuePreferences == "Capsule"}
Define constant variables at the top or in another file and use them instead of custom "String" values like "Capsule" here in the code. Especially when you are making comparison on them. When you write the same string multiple times, it is very east to make mistakes like writing `Caspule` instead of `Capsule` in one of those places, and it's hard to realize it.

2021-08-13 13:18 UTC, erdemalpay commented on src/components/Subscribe.svelte
> +                <button class="accordion"> Whant us to grind them? </button>
Is this really `Whant`?

2021-08-13 13:18 UTC, erdemalpay commented on src/components/Subscribe.svelte
> +        {#if valuePreferences == "Capsule"}
This is also ok but I would prefer putting conditions in the div above instead of duplicating it. That would look like more to other parts.

2021-08-13 13:18 UTC, erdemalpay commented on src/components/Subscribe.svelte
> +        </div>
I feel like this part is very similar for all 5 steps. Is it possible to create a component and use that component with each steps?

2021-08-13 13:18 UTC, erdemalpay commented on src/main.js
> +import App from './components/Subscribe.svelte';
I assume this is temporary thing right? Main page should not be Subscribe I guess.

2021-08-14 17:55 UTC, esralpay commented on src/components/Subscribe.svelte
> +    //$: priceEveryweek = valueQuantity == "250g" ? "7.20" : valueQuantity == "500g" ? "13.00" : valueQuantity == "1000g" ? "22.00" : "0";
removed

2021-08-14 17:59 UTC, esralpay commented on src/components/Subscribe.svelte
> +    let priceEveryweek = "";
priceEveryweek canged to priceEveryWeek, priceEvery2week canged to priceEvery2Week, priceEverymonth canged to priceEveryMonth

2021-08-17 07:47 UTC, esralpay commented on src/components/Subscribe.svelte
> +                class:selected={valuePreferences == "Capsule"}
"Capsule" "Filter" "Espresso" changed with capsule filter and espresso. I did not change other strings cause of not multiple uses.

2021-08-17 07:48 UTC, esralpay commented on src/components/Subscribe.svelte
> +                <button class="accordion"> Whant us to grind them? </button>
sorry changed

2021-08-17 07:48 UTC, esralpay commented on src/components/Subscribe.svelte
> +        {#if valuePreferences == "Capsule"}
Maybe someday you show me how to do

2021-08-17 07:51 UTC, esralpay commented on src/main.js
> +import App from './components/Subscribe.svelte';
just temporary

2021-08-17 08:13 UTC, esralpay commented on src/components/Subscribe.svelte
> +        </div>
ok lets look it together

2021-08-18 11:10 UTC, merged